### ISSUE TITLE
Checkpointing possibility

### ISSUE THREAD

**Issue by mherold1** [fplaza/mgs-canopy-algorithm#1]
Hello,

Thank you for the implementation. 
I had some issues running the canopy clustering succesfully. Either it takes very long or it gets stuck in the merging canopies step (maybe memory related).
Is it possible to pick up where the job was killed e.g. with the "--not_processed_points_file" option and if yes how would this work? 

Output from my run:
[cc_stderr.txt](https://github.com/fplaza/mgs-canopy-algorithm/files/38830/cc_stderr.txt)

**Comment by fplazaonate** [comment]
Hi,
One alternative consists in reducing the "stop_proportion_of_points" parameter from 1 to 0.6 (or less)
Some small canopies will be missing but the execution time will be significantly lower.
Hope this helps.
