### ISSUE TITLE
Result affected by qsub parameter

### ISSUE THREAD

**Issue by UKQIDA** [fplaza/mgs-canopy-algorithm#5]
Hi,
When I submitted a shell script file (run.sh) (cc.bin -n 16 -i /Path/gene.abundance.tab -o clusters_out -c profiles_out -p CAG_out --max_canopy_dist 0.1 --max_close_dist 0.4 --max_merge_dist 0.1 --min_step_dist 0.005 --max_num_canopy_walks 5 --stop_fraction 1 --canopy_size_stats_file progress_stat_file) via qsub, I found the result from different qsub parameter (linear) differed.
Why simply changing the thread number will cause the different result? Do you use any special treatment to the input in the cc.bin?

Regards,
Da

**Comment by fplazaonate** [comment]
Hi,
The canopy clustering algorithm does not generate reproducible results when you use multiple threads. This design drastically improves performance.

Best.
Florian
